[package]
name = "rs_ws281x_demo"
version = "0.1.0"
authors = ["Alex Beharrell <martiansoup>"]
edition = "2018"

[dependencies]
log = "0.4.11"
simple_logger = "1.11.0"
rs_ws281x = "0.3.1"
rand = "0.7"
